/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {
        // 1º Part
        // Thread stream1 = new Stream1();
        // Thread stream2 = new Thread(new Stream2());

        // System.err.println("Iniciando o programa");

        // stream1.start();
        // stream2.start();

        // System.err.println("Finalizando o programa");

        // 2º Part
        Thread helloWorld = new HelloWorld();

        helloWorld.start();
    }
}
